// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBICY6NomLUolk0P5_6thJNx4wFu2PgtWU',
    appId: '1:880827445601:web:56c1d65d2ba84d0ab2d520',
    messagingSenderId: '880827445601',
    projectId: 'weather-4eeaa',
    authDomain: 'weather-4eeaa.firebaseapp.com',
    storageBucket: 'weather-4eeaa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKFYPUYw9WojpV1RUBTC2N7GlXQu_eHZ0',
    appId: '1:880827445601:android:7e1ed714fe4b4190b2d520',
    messagingSenderId: '880827445601',
    projectId: 'weather-4eeaa',
    storageBucket: 'weather-4eeaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcY7uRhtpv0fnne-FicuZlMEN5MGbRIMg',
    appId: '1:880827445601:ios:de1ced8454270562b2d520',
    messagingSenderId: '880827445601',
    projectId: 'weather-4eeaa',
    storageBucket: 'weather-4eeaa.appspot.com',
    iosBundleId: 'com.example.weather',
  );
}
